Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "private_network", ip: "192.168.24.42"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.gui = false
  end

  config.vm.provision "shell", path: "setup.sh"

end
